//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UniVRM10.VRM10SpringBoneCollider))]
	public class PropertyProvider_UniVRM10_VRM10SpringBoneCollider : Unity.VisualScripting.SerializedPropertyProvider<UniVRM10.VRM10SpringBoneCollider>
	{
	}
}
